logging:
  level:
    org:
      springframework: DEBUG
spring:
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        output: 
          destination: create-account
          contentType: application/*+avro
      kafka:
        bindings:
          output:
            producer:
              messageKeyExpression: headers['messageKey']
        binder:
          brokers: localhost
          producer-properties:
            key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
            value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
            schema.registry.url: http://localhost:8081 
    schemaRegistryClient:
      endpoint: http://localhost:8081