logging:
  level:
    org:
      springframework: DEBUG
spring:
  cloud:
    stream:
      bindings:
        output: 
          destination: create_account
      kafka:
        binder:
          brokers: localhost
