logging:
  level:
    org:
      springframework: DEBUG
spring:
  cloud:
    stream:
      bindings:
        output: 
          destination: create_account
      kafka:
        bindings:
          output:
            producer:
              messageKeyExpression: headers['messageKey']
        binder:
          brokers: localhost
          producer-properties:
            key.serializer: "org.apache.kafka.common.serialization.StringSerializer"